# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='issuperuser',
            field=models.BooleanField(default=False),
        ),
    ]
