# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0003_auto_20160710_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
