//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cloudweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideShow
    {
        public int Id { get; set; }
        public string SlideName { get; set; }
        public string PhotoIds { get; set; }
        public string Effect { get; set; }
        public int Duration { get; set; }
        public string UserId { get; set; }
    }
}
