#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Alkometer.Resource", IsApplication=true)]

namespace Alkometer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int baconcocktail = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int beerbottle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int beercan = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int beerglass = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int beerkek = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bloodmary = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int contacts = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int drink = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int fruit = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int glass = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_arrow_back_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_arrow_back_white_36dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_arrow_back_white_48dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_camera = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_check_white_24dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_check_white_36dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_check_white_48dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_pie = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_tab_white = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int kek = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int konjakglass = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int pint = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ripple = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int shampoonbottle = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int shampoonglass = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int soda = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int winebottle = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int wineglass = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int AddButton = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int AddNewDrinkButton = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int AlkoProgressBar = 2131099654;
			
			// aapt resource value: 0x7f060019
			public const int AlkoTable = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int BeerBottleButton = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int BeerButton = 2131099674;
			
			// aapt resource value: 0x7f06001e
			public const int BeerKekButton = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int BloodButton = 2131099679;
			
			// aapt resource value: 0x7f06000c
			public const int CancelViewDeleteButton = 2131099660;
			
			// aapt resource value: 0x7f06003a
			public const int ContactAcceptCancelButton = 2131099706;
			
			// aapt resource value: 0x7f060039
			public const int ContactAcceptSaveButton = 2131099705;
			
			// aapt resource value: 0x7f06002e
			public const int ContactEditButtonLayout = 2131099694;
			
			// aapt resource value: 0x7f06002c
			public const int ContactEditImageView = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int ContactEditLayout = 2131099693;
			
			// aapt resource value: 0x7f06002f
			public const int ContactEditSaveButton = 2131099695;
			
			// aapt resource value: 0x7f060038
			public const int ContactNewButtonLayout = 2131099704;
			
			// aapt resource value: 0x7f060037
			public const int ContactNewImageView = 2131099703;
			
			// aapt resource value: 0x7f060036
			public const int ContactNewSurfaceView = 2131099702;
			
			// aapt resource value: 0x7f06000a
			public const int ContactViewImageView = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int ContactViewNameLabel = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int ContactViewNameText = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int ContactViewNumberLabel = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int ContactViewNumberText = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int ContactViewSaveButton = 2131099659;
			
			// aapt resource value: 0x7f060018
			public const int DrinkAcceptCancelButton = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int DrinkAcceptSaveButton = 2131099671;
			
			// aapt resource value: 0x7f060020
			public const int DrinkButton = 2131099680;
			
			// aapt resource value: 0x7f060015
			public const int DrinkButtonLayout = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int DrinkList = 2131099655;
			
			// aapt resource value: 0x7f060016
			public const int DrinkNewButtonLayout = 2131099670;
			
			// aapt resource value: 0x7f060030
			public const int EditNameLabel = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int EditNameText = 2131099697;
			
			// aapt resource value: 0x7f060034
			public const int EditNumberLabel = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int EditNumberText = 2131099701;
			
			// aapt resource value: 0x7f060032
			public const int EditSurnameLabel = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int EditSurnameText = 2131099699;
			
			// aapt resource value: 0x7f060021
			public const int FruitButton = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int GlassButton = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int KonjakButton = 2131099683;
			
			// aapt resource value: 0x7f060026
			public const int LabelAlcoholByVolume = 2131099686;
			
			// aapt resource value: 0x7f060005
			public const int LabelProgress = 2131099653;
			
			// aapt resource value: 0x7f060029
			public const int LabelVolume = 2131099689;
			
			// aapt resource value: 0x7f06003f
			public const int NewDrinkAboutEdit = 2131099711;
			
			// aapt resource value: 0x7f06003e
			public const int NewDrinkAboutText = 2131099710;
			
			// aapt resource value: 0x7f06003d
			public const int NewDrinkNameEdit = 2131099709;
			
			// aapt resource value: 0x7f06003c
			public const int NewDrinkNameText = 2131099708;
			
			// aapt resource value: 0x7f060024
			public const int PintButton = 2131099684;
			
			// aapt resource value: 0x7f060028
			public const int SeekBarAlcoholByVolume = 2131099688;
			
			// aapt resource value: 0x7f060004
			public const int SeekBarStrong = 2131099652;
			
			// aapt resource value: 0x7f06002b
			public const int SeekBarVolume = 2131099691;
			
			// aapt resource value: 0x7f060001
			public const int SeekLayout = 2131099649;
			
			// aapt resource value: 0x7f060025
			public const int ShampoonBottleButton = 2131099685;
			
			// aapt resource value: 0x7f06001c
			public const int ShampoonGlassButton = 2131099676;
			
			// aapt resource value: 0x7f060002
			public const int StrongText = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int TaskList = 2131099657;
			
			// aapt resource value: 0x7f060027
			public const int TextAlcoholByVolume = 2131099687;
			
			// aapt resource value: 0x7f060003
			public const int TextStrong = 2131099651;
			
			// aapt resource value: 0x7f06002a
			public const int TextVolume = 2131099690;
			
			// aapt resource value: 0x7f06001d
			public const int WineGlassButton = 2131099677;
			
			// aapt resource value: 0x7f060014
			public const int fragmentContainer = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int item_icon = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int item_title = 2131099667;
			
			// aapt resource value: 0x7f06003b
			public const int layout_root = 2131099707;
			
			// aapt resource value: 0x7f060000
			public const int meterlayout = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Alko = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContactsLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContactView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DrinksListFooter = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DrinkView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NewAlcoDrink = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int NewContactEdit = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int NewContactTakePhoto = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int NewDrinkAcceptAlert = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
